import React from "react";
import './index.css'
import { Row, Col } from 'antd'
import SERVICES from '../../image/features/SERVICES.png'
import ORACLE from '../../image/features/ORACLE.png'
import ARTWORKS from '../../image/features/ARTWORKS.png'
import DETECTION from '../../image/features/DETECTION.png'
import INFRASTRUCTURE from '../../image/features/INFRASTRUCTURE.png'
import CASES from  '../../image/features/CASES.png'
import FEES from '../../image/features/FEES.png'
import ROYALTIES from '../../image/features/ROYALTIES.png'
import SERVICESSolid from '../../image/features/SERVICESSolid.png'
import ORACLESolid from '../../image/features/ORACLESolid.png'
import ARTWORKSSolid from '../../image/features/ARTWORKSSolid.png'
import DETECTIONSolid from '../../image/features/DETECTIONSolid.png'
import INFRASTRUCTURESolid from '../../image/features/INFRASTRUCTURESolid.png'
import CASESSolid from  '../../image/features/CASESSolid.png'
import FEESSolid from '../../image/features/FEESSolid.png'
import ROYALTIESSolid from '../../image/features/ROYALTIESSolid.png'

function FeaturesPage() {
    return (
        <div className="features">
            <div className="features-content" data-aos="fade-up">
                <Row gutter={[70,100]}>
                    <Col xxl={6} xl={6} lg={12} md={24}>
                        <div className="features-content-item">
                            <div className="features-content-item-img">
                                <img src={SERVICES} />
                                <img src={SERVICESSolid} />
                            </div>
                            <div className="features-content-item-title">
                                INNOVATIVE NFT TRANSACTION SERVICES
                            </div>
                            <div className="features-content-item-text">
                                Convenient trading, innovative
                                auction, Collateralizing and
                                lending, NFT splitting, NFT
                                liquidity mining.
                            </div>
                        </div>
                    </Col>
                    <Col xxl={6} xl={6} lg={12} md={24}>
                        <div className="features-content-item">
                            <div className="features-content-item-img">
                                <img src={ORACLE} />
                                <img src={ORACLESolid} />
                            </div>
                            <div className="features-content-item-title">
                                AI BUILT-IN NFT ORACLE
                            </div>
                            <div className="features-content-item-text">
                                Provide a reference price for NFT
                                through algorithm intelligence.
                            </div>
                        </div>
                    </Col>
                    <Col xxl={6} xl={6} lg={12} md={24}>
                        <div className="features-content-item">
                            <div className="features-content-item-img">
                                <img src={ARTWORKS} />
                                <img src={ARTWORKSSolid} />
                            </div>
                            <div className="features-content-item-title">
                                AI GENERATED
                                ARTWORKS
                            </div>
                            <div className="features-content-item-text">
                                Create artworks generated by AI
                                which will be rewarded to liquidity
                                providers.
                            </div>
                        </div>
                    </Col>
                    <Col xxl={6} xl={6} lg={12} md={24}>
                        <div className="features-content-item">
                            <div className="features-content-item-img">
                                <img src={DETECTION} />
                                <img src={DETECTIONSolid} />
                            </div>
                            <div className="features-content-item-title">
                                DUPLICATE DETECTION
                            </div>
                            <div className="features-content-item-text">
                                Help users detect fake,
                                duplicate or similar NFTs using
                                AI technology to to enhance
                                copyright protection.
                            </div>
                        </div>
                    </Col>
                    <Col xxl={6} xl={6} lg={12} md={24}>
                        <div className="features-content-item">
                            <div className="features-content-item-img">
                                <img src={INFRASTRUCTURE} />
                                <img src={INFRASTRUCTURESolid} />
                            </div>
                            <div className="features-content-item-title">
                                SCALABLE CROSS-CHAIN
                                INFRASTRUCTURE
                            </div>
                            <div className="features-content-item-text">
                                Provide cross-chain services through
                                Solana, Polkadot and Polygon.
                            </div>
                        </div>
                    </Col>
                    <Col xxl={6} xl={6} lg={12} md={24}>
                        <div className="features-content-item">
                            <div className="features-content-item-img">
                                <img src={CASES} />
                                <img src={CASESSolid} />
                            </div>
                            <div className="features-content-item-title">
                            NFT LENDING
                            </div>
                            <div className="features-content-item-text">
                            Provide complete NFT lending methods, 
                            including the P2P model of mortgage of
                            NFT ERC20 tokens and the scheme of
                            direct mortgage of ERC721 tokens.
                            </div>
                        </div>
                    </Col>
                    <Col xxl={6} xl={6} lg={12} md={24}>
                        <div className="features-content-item">
                            <div className="features-content-item-img">
                                <img src={FEES} />
                                <img src={FEESSolid} />
                            </div>
                            <div className="features-content-item-title">
                                LOWER FEES
                            </div>
                            <div className="features-content-item-text">
                                Lower gas fees base on Solana,
                                Polkadot and Polygon.
                                The platform will take 1% revenue.
                            </div>
                        </div>
                    </Col>
                    <Col xxl={6} xl={6} lg={12} md={24}>
                        <div className="features-content-item">
                            <div className="features-content-item-img">
                                <img src={ROYALTIES} />
                                <img src={ROYALTIESSolid} />
                            </div>
                            <div className="features-content-item-title">
                                PERMANENT ROYALTIES
                            </div>
                            <div className="features-content-item-text">
                                Royalty information will be recorded at
                                creation. Creator will receive permanent
                                royalties benefit when NFTs transactions
                                in Banksy.
                            </div>
                        </div>
                    </Col>
                </Row>
            </div>
        </div>
    )
}

export default FeaturesPage